import{describe,expect,it}from'vitest';import{canTransition,containsSensitiveData,createWriterBrief,redactNarrative,validateSyntheticSubmission,writerBriefHasRawFields}from'../src/lib/incident';import fixture from'../incident-system/fixtures/synthetic-valid.json';
const reviewed={...fixture,status:'approved-brief',briefId:'brief_synthetic_000001',reviewReference:'review_synthetic',privacyReviewState:'verified',consentVerificationState:'verified',reviewedNamePermission:'verified-parties',reviewedQuotePermission:'verified-speakers',privateEvent:false,changeIdentities:false,generalizedEvent:'A fictional stool moved',reviewedWhyFunny:'The furniture caused administrative chaos',paraphrasedPunchline:'The stool requests a quieter table',reviewedSuggestedCharacter:'Vellum',deadline:null};
describe('incident privacy boundary',()=>{
 it('accepts only complete synthetic fixture',()=>expect(validateSyntheticSubmission(fixture).ok).toBe(true));
 it.each(['Meet at 123:456','account id: ABC-99','password=hunter2','credential secret-value','email test@example.com','phone +1 (555) 222-3333','ask @member'])('fails closed on sensitive input: %s',text=>expect(validateSyntheticSubmission({...fixture,whatHappened:text})).toEqual(expect.objectContaining({ok:false})));
 it('fully removes adversarial value spans',()=>{const raw='123:456 account id: ABC-99 password=hunter2 test@example.com +1 (555) 222-3333 @member';const safe=redactNarrative(raw);expect(safe).not.toMatch(/123:456|ABC-99|hunter2|test@example|555|member/i)});
 it('allows withdrawal from every active unpublished status',()=>{for(const status of ['received','privacy-review','needs-clarification','approved-brief','handed-to-writers','scripted','ip-review','founder-review','approved','scheduled']as const)expect(canTransition(status,'withdrawn')).toBe(true)});
 it('routes published content only to takedown review',()=>{expect(canTransition('published','takedown-review')).toBe(true);expect(canTransition('published','withdrawn')).toBe(false);expect(canTransition('published','archived')).toBe(false)});
 it('does not trust submitter name or quote booleans',()=>{const brief=createWriterBrief({...reviewed,reviewedNamePermission:'none',reviewedQuotePermission:'none',namesMayBeUsed:true,exactQuotesMayBeUsed:true});expect(brief.identityRule).toBe('anonymize-all');expect(brief.quoteRule).toBe('paraphrase-only')});
 it('permits names and quotes only from reviewer-verified states',()=>{const brief=createWriterBrief(reviewed);expect(brief.identityRule).toBe('verified-names-only');expect(brief.quoteRule).toBe('verified-quotes-only');expect(writerBriefHasRawFields(brief)).toBe(false)});
 it.each([{privateEvent:true},{changeIdentities:true}])('forces anonymization and paraphrase for privacy flags',flags=>{const brief=createWriterBrief({...reviewed,...flags});expect(brief.identityRule).toBe('anonymize-all');expect(brief.quoteRule).toBe('paraphrase-only')});
 it('rejects sensitive reviewed handoff instead of leaking',()=>expect(()=>createWriterBrief({...reviewed,generalizedEvent:'password=secret'})).toThrow(/Sensitive data/));
 it('never propagates arbitrary raw names or exact quotes',()=>{const brief=createWriterBrief({...reviewed,whatHappened:'Raw Alice said "password=secret"',whyFunny:'Raw Bob was mocked',whoWasInvolved:'Alice and Bob',suggestedPunchline:'Exact private quote'});expect(JSON.stringify(brief)).not.toMatch(/Alice|Bob|password|Exact private quote|mocked/i);expect(brief.generalizedEvent).toBe(reviewed.generalizedEvent);expect(brief.suggestedPunchline).toBe(reviewed.paraphrasedPunchline)});
 it('requires every reviewer-authored minimized field',()=>{for(const field of ['generalizedEvent','reviewedWhyFunny','paraphrasedPunchline'])expect(()=>createWriterBrief({...reviewed,[field]:''})).toThrow(/Reviewer-authored/)});
 it('blocks unverified privacy or consent handoff',()=>{expect(()=>createWriterBrief({...reviewed,privacyReviewState:'pending'})).toThrow();expect(()=>createWriterBrief({...reviewed,consentVerificationState:'unverified'})).toThrow()});
 it('detects direct sensitive content',()=>expect(containsSensitiveData('contact me at test@example.com')).toBe(true));
});
