$ErrorActionPreference='Stop'; $root=Split-Path -Parent $PSScriptRoot; $animation=Join-Path $root 'animation'
$premises=Get-Content (Join-Path $animation 'premises.json') -Raw|ConvertFrom-Json
if($premises.premises.Count-ne 30){throw 'Expected exactly 30 premises.'}; if((($premises.weights.psobject.Properties.Value|Measure-Object -Sum).Sum)-ne 100){throw 'Premise weights must total 100.'}
$ids=@(); foreach($p in $premises.premises){if($ids-contains $p.id){throw "Duplicate $($p.id)"};$ids+=$p.id;if(-not $p.fictional){throw "$($p.id) is not synthetic fiction."};$sum=($p.score|Measure-Object -Sum).Sum;if($sum-ne $p.total){throw "$($p.id) score mismatch."};if($p.duration-lt 15-or$p.duration-gt 45){throw "$($p.id) outside 15-45 seconds."}}
$scripts=Get-Content (Join-Path $animation 'scripts.json') -Raw|ConvertFrom-Json;if($scripts.scripts.Count-ne 10){throw 'Expected exactly 10 scripts.'}
$expected=@($premises.premises|Sort-Object total -Descending|Select-Object -First 10|ForEach-Object id|Sort-Object);$actual=@($scripts.scripts.id|Sort-Object);if(($expected-join',')-ne($actual-join',')){throw 'Scripts must be the top ten scored premises.'}
foreach($s in $scripts.scripts){if($s.duration-lt 15-or$s.duration-gt 45){throw "$($s.id) duration invalid."};$last=-1;foreach($beat in @('hook','setup','escalation','conflict','punchline')){$b=$s.$beat;if(-not$b.text-or$b.at-le$last-or$b.at-ge$s.duration){throw "$($s.id) invalid $beat."};$last=$b.at}}
$story=Get-Content (Join-Path $animation 'storyboards/manifest.json') -Raw|ConvertFrom-Json;if($story.storyboards.Count-ne 5){throw 'Expected exactly 5 storyboards.'};foreach($s in $story.storyboards){if(-not(Test-Path(Join-Path $root $s.file))-or-not$s.silentNote){throw "Invalid storyboard $($s.id)."}}
$library=Get-Content (Join-Path $animation 'library/manifest.json') -Raw|ConvertFrom-Json;if($library.characters.Count-ne 7-or$library.backgrounds.Count-ne 7-or$library.props.Count-lt 3-or$library.templates.Count-lt 1){throw 'Reusable library incomplete.'}
$rigFiles=Get-ChildItem (Join-Path $animation 'library/characters') -Filter 'CHR-*-v001.svg';if($rigFiles.Count-ne$library.characters.Count){throw 'Declared character count does not match rig files.'};foreach($rigFile in $rigFiles){try{[xml]$rig=Get-Content $rigFile.FullName -Raw}catch{throw "$($rigFile.Name) is invalid XML."};foreach($layer in $library.layerContract){if(-not$rig.SelectSingleNode("//*[@id='$layer']")){throw "$($rigFile.Name) missing declared layer $layer."}}}
$projects=Get-ChildItem (Join-Path $animation 'projects') -Directory;if($projects.Count-ne 3-or(($projects.Name|Sort-Object)-join',')-ne'TT-S01-001,TT-S02-001,TT-S07-001'){throw 'Expected S01/S02/S07 project candidates.'}
foreach($dir in $projects){$m=Get-Content (Join-Path $dir.FullName 'manifest.json') -Raw|ConvertFrom-Json;if($m.status-ne'render-candidate'-or$m.publication-ne'blocked'-or$m.frame-ne'1080x1920'-or$m.aspect-ne'9:16'){throw "$($dir.Name) exceeds status or format ceiling."};foreach($a in @('music','voice','sfx')){if($m.audio.$a-ne'intentionally-none'){throw "$($dir.Name) audio state missing."}};foreach($ext in @('*.vtt','*.srt','TRANSCRIPT.md','*TIMELINE*.svg','*POSTER*.svg')){if(-not(Get-ChildItem $dir.FullName -Filter $ext)){throw "$($dir.Name) missing $ext."}};$vtt=Get-Content (Get-ChildItem $dir.FullName -Filter '*.vtt') -Raw;foreach($block in ($vtt-split"`r?`n`r?`n")){if($block-match'-->'){$lines=@($block-split"`r?`n"|Select-Object -Skip 1);if($lines.Count-gt 2){throw "$($dir.Name) caption exceeds two lines."}}}}
$candidateText=(Get-ChildItem $animation -Recurse -File -Include *.json,*.svg,*.vtt,*.srt|Get-Content -Raw)-join"`n";if($candidateText-match'private message|account detail|alliance strateg|real coordinates|member identity'){throw 'Potential private data reference.'}
$lines=Get-Content (Join-Path $animation 'CHECKSUMS.sha256')|Where-Object{$_.Trim()};foreach($line in $lines){if($line-notmatch'^([0-9a-f]{64})  (.+)$'){throw 'Bad checksum line.'};$actual=(Get-FileHash -Algorithm SHA256 (Join-Path $root $Matches[2])).Hash.ToLower();if($actual-ne$Matches[1]){throw "Checksum mismatch $($Matches[2])"}}
$rights=Get-Content (Join-Path $root 'docs/ASSET_RIGHTS_REGISTER.md') -Raw;foreach($id in @('ANIM-LIB-001','ANIM-STORY-001','ANIM-CAND-001')){if($rights-notmatch$id){throw "Missing rights $id"}}
Write-Host 'Animation validation passed: 30 premises, 10 timed scripts, 5 storyboards, 3 blocked render candidates, reusable library, captions, privacy ceiling, checksums, and rights.'
