$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$dir=Join-Path $root 'incident-system'
foreach($f in @('submission','consent','restricted-record','writer-brief','withdrawal')){if(-not(Test-Path (Join-Path $dir "schemas/$f.schema.json"))){throw "Missing $f schema"};Get-Content (Join-Path $dir "schemas/$f.schema.json") -Raw|ConvertFrom-Json|Out-Null}
$policy=Get-Content (Join-Path $dir 'policy.json') -Raw|ConvertFrom-Json;if($policy.mode-ne'NO_COLLECTION'-or$policy.provider-ne'TBD'-or$policy.region-ne'TBD'){throw 'NO COLLECTION/provider gate changed.'};if(@($policy.retention.psobject.Properties.Value|Where-Object{$_-ne'TBD'}).Count){throw 'Retention duration invented.'}
foreach($status in $policy.statuses){foreach($to in $policy.transitions.$status){if($policy.statuses-notcontains$to){throw "Unknown transition $status->$to"}}};if($policy.transitions.received-contains'approved'){throw 'Unsafe direct approval transition.'}
foreach($status in @('received','privacy-review','needs-clarification','approved-brief','handed-to-writers','scripted','ip-review','founder-review','approved','scheduled')){if($policy.transitions.$status-notcontains'withdrawn'){throw "$status must permit withdrawal while unpublished."}};if(($policy.transitions.published-join',')-ne'takedown-review'){throw 'Published content must route only to takedown-review.'}
$consent=Get-Content (Join-Path $dir 'schemas/consent.schema.json') -Raw|ConvertFrom-Json;foreach($field in @('reviewedNamePermission','reviewedQuotePermission','verificationState')){if($consent.required-notcontains$field){throw "Consent schema missing required reviewer-derived $field."}}
$writer=Get-Content (Join-Path $dir 'schemas/writer-brief.schema.json') -Raw|ConvertFrom-Json;$forbidden=@('rawNarrative','contactRef','consentRecordId','recordId','whoWasInvolved','capturedAt');foreach($f in $forbidden){if($writer.properties.psobject.Properties.Name-contains$f){throw "Writer schema leaks $f"}}
$restricted=Get-Content (Join-Path $dir 'schemas/restricted-record.schema.json') -Raw|ConvertFrom-Json;foreach($field in @('generalizedEvent','reviewedWhyFunny','paraphrasedPunchline')){if($restricted.properties.psobject.Properties.Name-notcontains$field){throw "Restricted review schema missing $field."}};if(-not$restricted.allOf){throw 'Verified review must conditionally require minimized fields.'}
$prototype=Get-Content (Join-Path $root 'design/incident-system/disabled-prototype.html') -Raw;if($prototype-match'<form\b|\baction=|<script\b|fetch\(|XMLHttpRequest|localStorage|sessionStorage|indexedDB'){throw 'Prototype contains collection capability.'};foreach($label in @('What happened','Why was it funny','Who was involved','Names may be used','Exact quotes may be used','event is private','Change all identities','Suggested character','Suggested punchline','Relevant deadline','permission to adapt')){if($prototype-notmatch[regex]::Escape($label)){throw "Prototype missing $label"}}
$all=(Get-ChildItem $dir -Recurse -File|Get-Content -Raw)-join"`n";if($all-match'https?://(?!json-schema\.org)|@(?:gmail|outlook|yahoo)|\b\d{2,4}[,:]\d{2,4}\b'){throw 'Live endpoint or real-looking data detected.'}
$fixture=Get-Content (Join-Path $dir 'fixtures/synthetic-valid.json') -Raw|ConvertFrom-Json;if(-not$fixture.permissionToAdapt-or$fixture.whatHappened-notmatch'fictional'){throw 'Valid fixture must be explicit synthetic fiction.'}
$utilities=Get-Content (Join-Path $root 'src/lib/incident.ts') -Raw;foreach($rule in @('privacyReviewState','consentVerificationState','reviewedNamePermission','reviewedQuotePermission','privateEvent','changeIdentities','containsSensitiveData')){if($utilities-notmatch$rule){throw "Privacy utility missing $rule enforcement."}}
foreach($rawUse in @('input.whatHappened','input.whyFunny','input.suggestedPunchline')){if($utilities.Contains($rawUse)){throw "Writer handoff reads raw field $rawUse."}};foreach($reviewedField in @('input.generalizedEvent','input.reviewedWhyFunny','input.paraphrasedPunchline')){if(-not$utilities.Contains($reviewedField)){throw "Writer handoff missing reviewed field $reviewedField."}}
Write-Host 'Incident validation passed: five schemas, NO COLLECTION, TBD provider/retention, safe transitions/RBAC, minimized writer fields, synthetic fixtures, and disabled complete prototype.'
